### ISSUE TITLE
Update guide based on 2023 changes to the platform

### ISSUE THREAD

**Issue by sigdestad** [enonic/doc-developer-101#44]
Read the intro to enonic before starting
Base the docs on 7.13 + Content Studio 5 (4.6 will be labelled 5)
Images should be annotated with pixel relative actual size.

---
- [x] https://github.com/enonic/doc-developer-101/issues/68

- [x] https://github.com/enonic/doc-developer-101/issues/48

- [x] https://github.com/enonic/doc-developer-101/issues/49

- [x] https://github.com/enonic/doc-developer-101/issues/50

- [x] https://github.com/enonic/doc-developer-101/issues/51

- [ ] New "traditional cms" chapter showing how to use XP not in headless mode?

- [x] https://github.com/enonic/doc-developer-101/issues/56

- [x] https://github.com/enonic/doc-developer-101/issues/58

- [x] https://github.com/enonic/doc-developer-101/issues/60

- [x] https://github.com/enonic/doc-developer-101/issues/62

- [x] https://github.com/enonic/doc-developer-101/issues/64

- [x] https://github.com/enonic/doc-developer-101/issues/66

- [x] https://github.com/enonic/doc-developer-101/issues/67

- [ ] https://github.com/enonic/doc-developer-101/issues/71
